### PR TITLE
Added scopes for multiple ids and latitude/longitude

### PR DESCRIPTION
**Pull request by nickghughes**
Uses gem "geokit-rails" to handle ordering breweries by nearest.

### CODE REVIEW

**Comment by chrisjm** [comment]
Heya @nickghughes ! I was finally able to get ruby set back up on my system and was able to get this set up locally. Works great!

**I think the only change I will request is to name the `by_coords` scope to `by_distance`. It seems to make the most sense given what it returns.** Once that's done, I'll merge and deploy!

This is a great starting point to add more scopes using the rest of the [scopes](https://github.com/geokit/geokit-rails), so thank you very much! 🍻 

As a side note, you may have seen on the Discord server that there is an active effort to switch to a NodeJS REST API. While that's the roadmap, I'm not sure when that will be complete and it never hurts to have multiple versions of an API server available.

**Comment by nickghughes** [comment]
@chrisjm thanks, just updated! Let me know if there's anything else you might want to change

**Comment by chrisjm** [comment]
Awesome, thank you! I'll get this merged and deployed shortly!

If you don't mind updating the docs with the new scope you implemented, I'd really appreciate it! https://www.openbrewerydb.org/documentation/01-listbreweries

Thank you so much for your contribution @nickghughes ! 🍻

**Comment by nickghughes** [comment]
done, and no problem! Excited to use the new scope

**Pull request merged**
