### PR TITLE
issue #41

### PR DESCRIPTION
**Pull request by chatpitre**
Just formatting the query. The results are now returned (not [] anymore).

### CODE REVIEW

**Comment by chrisjm** [comment]
Awesome! Thank you @chatpitre! I'll take a look and test soon! 🍻

**Comment by chatpitre** [comment]
I couldn't add unit test because of Elasticsearch. My computer was laggy and frozen while this tool is up. I had to change the timeout in the service to 5 minutes to just start it ! My computer was not really good in 2014, now it's a potato. I will take a look maybe on an other issue to just use postgres and not Elasticsearch anymore !

Cheers and take care 🍻

**Comment by chrisjm** [comment]
@chatpitre Haha, I hear you on slow computers. And no worries about not being able to test. The Elasticsearch requirement is annoying for dev, I know.

Don't spend too much time re: #22 (remove ElasticSearch). I think I have a solution that's almost complete. I will let you know!

**Comment by chrisjm** [comment]
Tested and merged! Thanks so much, @chatpitre ! 🍻

**Pull request merged**
